spring:
  application:
    name: ownBang
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    elasticsearch:
      client:
        uris: http://localhost:9200

  main:
    allow-bean-definition-overriding: true

  school:
    api: ${SCHOOL_API_KEY}

  location:
    api: ${LOCATION_API_KEY}

server:
  port: ${PORT}
  ssl:
    enabled: false

openvidu:
  url: ${OPENVIDU_URL}
  secret: ${OPENVIDU_SECRET}

elasticsearch:
  host: ${ELASTICSEARCH_HOST}
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}
