spring:
  application:
    name: ownBang
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${PORT}
  ssl:
    enabled: false

openvidu:
  url: ${ OPENVIDU_URL }
  secret: ${ OPENVIDU_SECRET }

cloud:
  aws:
    credentials:
      accessKey: ${aws_accessKey}
      secretKey: ${aws_secretKey}
    region:
      static: ${aws_region}
    s3:
      bucket: ${aws_s3bucket}

